library/config/routes.rb
Rails.application.routes.draw do


  get 'sessions/new'

  get 'users/new'

  get 'users/edit'

  get 'users/show'

  root "users#index"

  get "/login", to: "sessions#new"

  post "/sessions/new", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"
  resources :liberry_users

  resources :users do
    resources :liberries
  end

end

library/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

library/app/models/liberry.rb
class Liberry < ApplicationRecord
  has_many :liberry_users, dependent: :destroy
  has_many :users, through: :liberry_users
end

library/app/models/liberry_user.rb
class LiberryUser < ApplicationRecord
  belongs_to :liberry
  belongs_to :user
end

library/app/models/user.rb
class User < ApplicationRecord
  has_many :liberry_users, dependent: :destroy
  has_many :liberries, through: :liberry_users
  has_secure_password

  def self.confirm(params)
   @user = User.find_by({email: params[:email]})
   @user ? @user.authenticate(params[:password]) : false
 end
end

library/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

library/app/controllers/liberries_controller.rb
class LiberriesController < ApplicationController
  before_action :set_liberry, only: [:show, :edit, :update, :destroy]

  # GET /liberries
  # GET /liberries.json
  def index
    @liberries = Liberry.all
  end

  # GET /liberries/1
  # GET /liberries/1.json
  def show
  end

  # GET /liberries/new
  def new
    @liberry = Liberry.new
  end

  # GET /liberries/1/edit
  def edit
  end

  # POST /liberries
  # POST /liberries.json
  def create
    @liberry = Liberry.new(liberry_params)

    respond_to do |format|
      if @liberry.save
        format.html { redirect_to @liberry, notice: 'Liberry was successfully created.' }
        format.json { render :show, status: :created, location: @liberry }
      else
        format.html { render :new }
        format.json { render json: @liberry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /liberries/1
  # PATCH/PUT /liberries/1.json
  def update
    respond_to do |format|
      if @liberry.update(liberry_params)
        format.html { redirect_to @liberry, notice: 'Liberry was successfully updated.' }
        format.json { render :show, status: :ok, location: @liberry }
      else
        format.html { render :edit }
        format.json { render json: @liberry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /liberries/1
  # DELETE /liberries/1.json
  def destroy
    @liberry.destroy
    respond_to do |format|
      format.html { redirect_to liberries_url, notice: 'Liberry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_liberry
      @liberry = Liberry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def liberry_params
      params.require(:liberry).permit(:name, :floor_count, :florr_area)
    end
end

library/app/controllers/liberry_users_controller.rb
class LiberryUsersController < ApplicationController
  before_action :set_liberry_user, only: [:show, :edit, :update, :destroy]

  # GET /liberry_users
  # GET /liberry_users.json
  def index
    @liberry_users = LiberryUser.all
  end

  # GET /liberry_users/1
  # GET /liberry_users/1.json
  def show
  end

  # GET /liberry_users/new
  def new
    @liberry_user = LiberryUser.new
  end

  # GET /liberry_users/1/edit
  def edit
  end

  # POST /liberry_users
  # POST /liberry_users.json
  def create
    @liberry_user = LiberryUser.new(liberry_user_params)

    respond_to do |format|
      if @liberry_user.save
        format.html { redirect_to @liberry_user, notice: 'Liberry user was successfully created.' }
        format.json { render :show, status: :created, location: @liberry_user }
      else
        format.html { render :new }
        format.json { render json: @liberry_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /liberry_users/1
  # PATCH/PUT /liberry_users/1.json
  def update
    respond_to do |format|
      if @liberry_user.update(liberry_user_params)
        format.html { redirect_to @liberry_user, notice: 'Liberry user was successfully updated.' }
        format.json { render :show, status: :ok, location: @liberry_user }
      else
        format.html { render :edit }
        format.json { render json: @liberry_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /liberry_users/1
  # DELETE /liberry_users/1.json
  def destroy
    @liberry_user.destroy
    respond_to do |format|
      format.html { redirect_to liberry_users_url, notice: 'Liberry user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_liberry_user
      @liberry_user = LiberryUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def liberry_user_params
      params.require(:liberry_user).permit(:liberry_id, :user_id)
    end
end

library/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if User.confirm(params)
      flash[:notice] = "Successfully logged in."
      redirect_to user_path @user.id
    else
      #error
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Successfully logged out."
    redirect_to root_path
  end
end

library/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :first_name, :last_name, :password)
    end
end

library/app/helpers/application_helper.rb
module ApplicationHelper
end

library/app/helpers/liberries_helper.rb
module LiberriesHelper
end

library/app/helpers/liberry_users_helper.rb
module LiberryUsersHelper
end

library/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in
    session[:user_id] = @user.id
    @current_user = @user
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
end

library/app/helpers/users_helper.rb
module UsersHelper
end

library/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <ul>
     <% if current_user %>
       <li><%= link_to "Profile", user_path(current_user) %></li>
       <li><%= link_to "Log Out", logout_path, method: "DELETE" %></li>
     <% else %>
       <li><%= link_to "Create Account", new_user_path %></li>
       <li><%= link_to "Log In", login_path %></li>
     <% end %>
    </ul>

    <div class="container">
      <!-- ... -->
       <% flash.each do |name, msg| %>
         <p>
           <small> <%= name.capitalize %>: <%= msg %> </small>
         </p>
       <% end %>
     <%= yield %>

    </div>
  </body>
</html>

library/app/views/liberries/_form.html.erb
<%= form_for(liberry) do |f| %>
  <% if liberry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(liberry.errors.count, "error") %> prohibited this liberry from being saved:</h2>

      <ul>
      <% liberry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :floor_count %>
    <%= f.number_field :floor_count %>
  </div>

  <div class="field">
    <%= f.label :florr_area %>
    <%= f.number_field :florr_area %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

library/app/views/liberries/edit.html.erb
<h1>Editing Liberry</h1>

<%= render 'form', liberry: @liberry %>

<%= link_to 'Show', @liberry %> |
<%= link_to 'Back', liberries_path %>

library/app/views/liberries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liberries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Floor count</th>
      <th>Florr area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @liberries.each do |liberry| %>
      <tr>
        <td><%= liberry.name %></td>
        <td><%= liberry.floor_count %></td>
        <td><%= liberry.floor_area %></td>
        <td><%= link_to 'Show', liberry_user_path(liberry) %></td>
        <td><%= link_to 'Edit', edit_liberry_user_path(liberry) %></td>
        <td><%= link_to 'Destroy', liberry_user_path(liberry), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Liberry', new_liberry_user_path %>

library/app/views/liberries/new.html.erb
<h1>New Liberry</h1>

<%= render 'form', liberry: @liberry %>

<%= link_to 'Back', liberries_path %>

library/app/views/liberries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @liberry.name %>
</p>

<p>
  <strong>Floor count:</strong>
  <%= @liberry.floor_count %>
</p>

<p>
  <strong>Florr area:</strong>
  <%= @liberry.florr_area %>
</p>

<%= link_to 'Edit', edit_liberry_path(@liberry) %> |
<%= link_to 'Back', liberries_path %>

library/app/views/liberry_users/_form.html.erb
<%= form_for(liberry_user) do |f| %>
  <% if liberry_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(liberry_user.errors.count, "error") %> prohibited this liberry_user from being saved:</h2>

      <ul>
      <% liberry_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :liberry_id %>
    <%= f.text_field :liberry_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

library/app/views/liberry_users/edit.html.erb
<h1>Editing Liberry User</h1>

<%= render 'form', liberry_user: @liberry_user %>

<%= link_to 'Show', @liberry_user %> |
<%= link_to 'Back', liberry_users_path %>

library/app/views/liberry_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Liberry Users</h1>

<table>
  <thead>
    <tr>
      <th>Liberry</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @liberry_users.each do |liberry_user| %>
      <tr>
        <td><%= liberry_user.liberry.name %></td>
        <td><%= liberry_user.user.email %></td>
        <td><%= link_to 'Show', liberry_user %></td>
        <td><%= link_to 'Edit', edit_liberry_user_path(liberry_user) %></td>
        <td><%= link_to 'Destroy', liberry_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Liberry User', new_liberry_user_path %>

library/app/views/liberry_users/new.html.erb
<h1>New Liberry User</h1>

<%= render 'form', liberry_user: @liberry_user %>

<%= link_to 'Back', liberry_users_path %>

library/app/views/liberry_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Liberry:</strong>
  <%= @liberry_user.liberry.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @liberry_user.user.email %>
</p>

<%= link_to 'Edit', edit_liberry_user_path(@liberry_user) %> |
<%= link_to 'Back', liberry_users_path %>

library/app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

library/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

library/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Libraries</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Libraries', user_liberries_path(user) %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

library/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

library/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>